<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>4.0.5</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>school.sptech</groupId>
	<artifactId>exercicio-testes-unitarios-spring</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>exercicio-testes-unitarios-spring</name>
	<description>Exercício de testes unitários Spring Boot</description>
	<url/>
	<licenses>
		<license/>
	</licenses>
	<developers>
		<developer/>
	</developers>
	<scm>
		<connection/>
		<developerConnection/>
		<tag/>
		<url/>
	</scm>
	<properties>
		<java.version>21</java.version>
		<jacoco.coverage.minimum>0.0</jacoco.coverage.minimum>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-h2console</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-validation</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webmvc</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
			<version>3.0.2</version>
		</dependency>

		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-validation-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webmvc-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.jacoco</groupId>
				<artifactId>jacoco-maven-plugin</artifactId>
				<version>0.8.14</version>
				<executions>

					<execution>
						<id>prepare-agent</id>
						<goals><goal>prepare-agent</goal></goals>
					</execution>

					<execution>
						<id>report</id>
						<phase>verify</phase>
						<goals><goal>report</goal></goals>
					</execution>

					<execution>
						<!-- Quando o id é "default-cli",
						essa configuração é utilizada quando o goal é executado diretamente pela linha de comando,
						por exemplo: mvn jacoco:check -->
						<id>default-cli</id>
						<goals><goal>check</goal></goals>
						<configuration>
							<includes>
								<include>school/sptech/exerciciotestesunitariosspring/service/*</include>
							</includes>
							<rules>
								<rule>
									<element>PACKAGE</element>
									<limits>
										<limit>
											<counter>BRANCH</counter>
											<value>COVEREDRATIO</value>
											<minimum>${jacoco.coverage.minimum}</minimum>
										</limit>
									</limits>
								</rule>
							</rules>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

	<profiles>
		<profile>
			<id>coverage-10</id>
			<properties>
				<jacoco.coverage.minimum>0.10</jacoco.coverage.minimum>
			</properties>
		</profile>
		<profile>
			<id>coverage-20</id>
			<properties>
				<jacoco.coverage.minimum>0.20</jacoco.coverage.minimum>
			</properties>
		</profile>
		<profile>
			<id>coverage-30</id>
			<properties>
				<jacoco.coverage.minimum>0.30</jacoco.coverage.minimum>
			</properties>
		</profile>
		<profile>
			<id>coverage-40</id>
			<properties>
				<jacoco.coverage.minimum>0.40</jacoco.coverage.minimum>
			</properties>
		</profile>
		<profile>
			<id>coverage-50</id>
			<properties>
				<jacoco.coverage.minimum>0.50</jacoco.coverage.minimum>
			</properties>
		</profile>
		<profile>
			<id>coverage-60</id>
			<properties>
				<jacoco.coverage.minimum>0.60</jacoco.coverage.minimum>
			</properties>
		</profile>
		<profile>
			<id>coverage-70</id>
			<properties>
				<jacoco.coverage.minimum>0.70</jacoco.coverage.minimum>
			</properties>
		</profile>
		<profile>
			<id>coverage-80</id>
			<properties>
				<jacoco.coverage.minimum>0.80</jacoco.coverage.minimum>
			</properties>
		</profile>
		<profile>
			<id>coverage-90</id>
			<properties>
				<jacoco.coverage.minimum>0.90</jacoco.coverage.minimum>
			</properties>
		</profile>
		<profile>
			<id>coverage-100</id>
			<properties>
				<jacoco.coverage.minimum>1.00</jacoco.coverage.minimum>
			</properties>
		</profile>

	</profiles>

</project>
